import {FAddress} from '..';

export type EnumerationListOnMap = {
  ada: string;
  adi: undefined;
  adresBilesenKimlikNo: number;
  bagimsizBolumler: FAddress[];
  bilesenAdi: string;
  binaNo: number;
  binaTur: undefined;
  binaTurFormatted: string;
  binaYapiTipi: number;
  blokAdi: undefined;
  csbmAdiReadonly: undefined;
  csbmKayitNo: number;
  disKapiNo1: number;
  disKapiNo2: undefined;
  disKapiNoFormatted: string;
  esKayitNo: undefined;
  father: undefined;
  hataliVeri: boolean;
  hataliVeriler: undefined;
  kayitNo: number;
  kimlikNo: number;
  maksBinaDurum: number;
  maksBinaDurumFormatted: string;
  maksBinaNumaratajTipi: number;
  maksBinaNumaratajTipiFormatted: string;
  metrukBinaAciklama: undefined;
  metrukBinaFormatted: string;
  metrukBinaSayi: undefined;
  metrukBinaTarih: undefined;
  note: undefined;
  pafta: undefined;
  parsel: string;
  postaKodu: undefined;
  siteAdi: undefined;
  versiyon: undefined;
  yapiKayitBelgeFormatted: string;
  yapiKayitBelgeSayi: undefined;
  yapiKayitBelgeTarih: undefined;
  yapiYadaDigerYapiId: undefined;
  yolAltiKatSayisi: undefined;
  yolUstuKatSayisi: undefined;
};
